if(typeof PrebidImpressionController!=='function'){class PrebidImpressionController{prebidImpressions=[];auctions={};slotAuctions={};constructor(){}
newPrebidImpression(slot,response){let pbi=new PrebidImpression(slot,response);let auctionIndentity=pbi.ad_unit_code+pbi.refresh_count.toString();if(typeof this.auctions[auctionIndentity]=='undefined'){this.auctions[auctionIndentity]=[];}
if(typeof this.slotAuctions[pbi.ad_unit_code]=='undefined'){this.slotAuctions[pbi.ad_unit_code]=[];}
if(this.auctions[auctionIndentity].filter(e=>e.request_id==pbi.request_id).length==0){this.auctions[auctionIndentity].push(pbi);this.prebidImpressions.push(pbi);this.slotAuctions[pbi.ad_unit_code].push(pbi);pbi.fire();}}}
window.PrebidImpressionController=PrebidImpressionController}
if(typeof PrebidImpression!=='function'){class PrebidImpression{storeUrl='/detroitchicago/bluemonkey.gif';fired=false;advertiser_domains=null;constructor(slot,response){let t=this;t.request_id=response.requestId;t.from_cache=(typeof response.from_cache=='undefined'?0:1);t.pageview_id=_ezaq["page_view_id"];t.auction_id=response.auctionId;t.ad_unit_code=slot.getSlotElementId();t.adapter_code=response.adapterCode;if(typeof response.meta.advertiserDomains!='undefined'){t.advertiser_domains=response.meta.advertiserDomains.join(',');}
t.original_cpm=response.originalCpm;t.cpm=response.cpm;t.adjustment=isNaN(response.cpm/response.originalCpm)?null:(response.cpm/response.originalCpm);t.media_type=(response.mediaType=='banner')?'display':response.mediaType;t.time_to_respond=(typeof response.timeToRespond==='undefined')?null:response.timeToRespond;t.response_size=(typeof response.size==='undefined')?null:response.size;let reqSize=slot.getSizes()[0].width.toString()+'x'+slot.getSizes()[0].height.toString();t.request_size=(typeof reqSize==='undefined')?null:reqSize;t.domain_id=parseInt(slot.getTargeting('d')[0]);t.form_factor_id=parseInt(slot.getTargeting('plat')[0]);t.position_type=parseInt(slot.getTargeting('pt')[0]);t.stat_source_id=parseInt(epbjs.SS[t.adapter_code]);t.refresh_count=typeof(slot.getTargeting('alc')[0]!='number')?0:parseInt(slot.getTargeting('alc')[0]);t.source=response.source;t.ab_test_id=_ezaq['ab_test_id'];}
outputPrebidImpression(){let t=this;let outputProperties=['pageview_id','auction_id','ad_unit_code','adapter_code','advertiser_domains','original_cpm','cpm','adjustment','media_type','time_to_respond','request_size','response_size','domain_id','form_factor_id','position_type','stat_source_id','refresh_count','from_cache','source','ab_test_id'];let returnModel={};for(let k in this){if(outputProperties.includes(k)){returnModel[k]=t[k];}}
return returnModel;}
getBaseUrl(){if((typeof window._ez_sa!=="undefined"&&window._ez_sa==true)||(typeof window.ezWp!=='undefined'&&window.ezWp===true)){return "https://g.ezoic.net";}else{return window.location.protocol+"//"+document.location.hostname;}}
fire(){let request=new XMLHttpRequest();request.open('POST',this.getBaseUrl()+this.storeUrl+'?e='+btoa(JSON.stringify(this.outputPrebidImpression())),true);request.send();this.fired=true;}}
window.PrebidImpression=PrebidImpression}